services:
  redis_app:
    image: redis_app
    container_name: redis_app
    restart: always
    ports:
      - ${API_PORT}:${API_PORT}
      - 2375:2375
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${API_PORT}/"]
      interval: 30s
      timeout: 30s
      retries: 10
      start_period: 30s
    init: true
    build: .
    env_file:
      - .env
    networks:
      - webservice_network

  redis:
    image: redis:7.4
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
      - ./redis.conf:/etc/redis/redis.conf
    networks:
      - webservice_network


volumes:
  data:

networks:
  webservice_network:
    name: webservice_network
